export const APP_JS = String.raw`
(function(){
var state={profile:null,projects:[],current:null,entries:[],students:[],stage:'during',classMode:false};
var gate=document.getElementById('gate'),app=document.getElementById('app'),side=document.getElementById('side'),main=document.getElementById('mainContent'),classEl=document.getElementById('classView');
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
var today=function(){return new Date().toISOString().slice(0,10)};
function toast(message){var el=document.getElementById('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.add('hidden')},3500)}
async function api(path,options){options=options||{};options.cache='no-store';var res=await fetch(path,options);var data=await res.json().catch(function(){return {}});if(res.status===401){showLogin();throw new Error(data.error||'다시 로그인해 주세요.')}if(!res.ok)throw new Error(data.error||'잠시 후 다시 시도해 주세요.');return data}
function submitButton(e){return e.submitter||e.currentTarget.querySelector('button[type="submit"]')}
function busy(btn,on,label){if(!btn)return;if(on){btn.dataset.label=btn.textContent;btn.textContent=label||'처리 중…';btn.disabled=true}else{btn.textContent=btn.dataset.label||btn.textContent;btn.disabled=false}}
function openDialog(id){document.getElementById(id).showModal()}function closeDialog(id){document.getElementById(id).close()}
function showLogin(){state={profile:null,projects:[],current:null,entries:[],students:[],stage:'during',classMode:false};app.classList.remove('is-loading');app.classList.add('hidden');gate.classList.remove('hidden')}
function setNavVisible(on){document.getElementById('viewTabs').classList.toggle('hidden',!on);document.getElementById('newProjectTop').classList.toggle('hidden',!on||!state.profile||state.profile.role!=='student')}
function editable(){return !!(state.current&&state.current.can_edit)}
function projectMembers(p){if(!p||!p.member_names)return [];try{var value=JSON.parse(p.member_names);return Array.isArray(value)?value:[]}catch(e){return String(p.member_names).split(/[,;\n]+/).filter(Boolean)}}
function projectOwnerLabel(p){return p&&p.grow_type==='group'?(p.group_name||'모둠'):p.student_name}
document.querySelectorAll('[data-close]').forEach(function(b){b.onclick=function(){closeDialog(b.dataset.close)}});
document.getElementById('photoInput').onchange=function(e){var file=e.target.files[0],img=document.getElementById('photoPreview');if(!file){img.style.display='none';return}img.src=URL.createObjectURL(file);img.style.display='block'};

document.getElementById('gateForm').onsubmit=async function(e){e.preventDefault();var form=e.currentTarget,f=new FormData(form),btn=submitButton(e);busy(btn,true,'로그인 중…');try{var data=await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({classCode:f.get('classCode'),name:f.get('name'),pin:f.get('pin'),role:f.get('role')})});form.reset();syncRoleChoice();await start(data.account)}catch(err){toast(err.message)}finally{busy(btn,false)}};
function syncRoleChoice(){var teacher=document.querySelector('#gateForm input[name="role"]:checked').value==='teacher';document.getElementById('teacherSignupOpen').classList.toggle('hidden',!teacher)}
document.querySelectorAll('#gateForm input[name="role"]').forEach(function(r){r.onchange=syncRoleChoice});
document.getElementById('teacherSignupOpen').onclick=function(){var g=document.getElementById('gateForm'),f=document.getElementById('teacherSignupForm');f.reset();f.elements.namedItem('classCode').value=g.elements.namedItem('classCode').value;f.elements.namedItem('name').value=g.elements.namedItem('name').value;openDialog('teacherSignupDialog')};
document.getElementById('teacherSignupForm').onsubmit=async function(e){e.preventDefault();var form=e.currentTarget,f=new FormData(form),pin=String(f.get('pin')),btn=submitButton(e);if(!/^\d{4}$/.test(pin)||pin!==String(f.get('confirmPin'))){toast('네 자리 비밀번호를 똑같이 두 번 입력해 주세요.');return}busy(btn,true,'만드는 중…');try{var data=await api('/api/auth/teacher-signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({classCode:f.get('classCode'),name:f.get('name'),signupCode:f.get('signupCode'),pin:pin})});form.reset();document.getElementById('gateForm').reset();syncRoleChoice();closeDialog('teacherSignupDialog');await start(data.account);toast('교사 계정을 만들었어요. 이제 학생 계정을 추가해 보세요.')}catch(err){toast(err.message)}finally{busy(btn,false)}};
async function start(account){state.profile=account;state.classMode=account.role==='teacher';gate.classList.add('hidden');app.classList.remove('hidden');app.classList.add('is-loading');document.getElementById('profileLine').textContent=account.class_code+' · '+account.name+(account.role==='teacher'?' 선생님':'');registerTools();if(account.must_change_pin){app.classList.remove('is-loading');document.getElementById('studentView').classList.add('hidden');classEl.classList.add('hidden');setNavVisible(false);document.getElementById('newEntryTop').classList.add('hidden');document.getElementById('changePinForm').reset();openDialog('changePinDialog');return}setNavVisible(true);try{await refreshAll();await render()}finally{app.classList.remove('is-loading')}}
document.getElementById('logoutBtn').onclick=async function(){try{await fetch('/api/auth/logout',{method:'POST'})}finally{showLogin();toast('로그아웃했어요.')}};
document.getElementById('changePinDialog').addEventListener('cancel',function(e){if(state.profile&&state.profile.must_change_pin)e.preventDefault()});
document.getElementById('changePinForm').onsubmit=async function(e){e.preventDefault();var f=new FormData(e.currentTarget),a=String(f.get('newPin')),b=String(f.get('confirmPin')),btn=submitButton(e);if(!/^\d{4}$/.test(a)||a!==b){toast('새 네 자리 비밀번호를 똑같이 입력해 주세요.');return}busy(btn,true,'저장 중…');try{var data=await api('/api/auth/change-pin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({currentPin:f.get('currentPin'),newPin:a})});state.profile=data.account;closeDialog('changePinDialog');setNavVisible(true);await refreshAll();await render();toast('새 비밀번호로 바꿨어요.')}catch(err){toast(err.message)}finally{busy(btn,false)}};

async function loadProjects(){var data=await api('/api/projects');state.projects=data.projects||[];var old=state.current&&state.current.id;state.current=state.projects.find(function(p){return p.id===old})||state.projects.find(function(p){return p.can_edit})||state.projects[0]||null;if(state.current)await loadEntries();else state.entries=[]}
async function loadEntries(){var data=await api('/api/observations?projectId='+encodeURIComponent(state.current.id));state.entries=data.observations||[]}
async function refreshAll(){await loadProjects();if(state.profile&&state.profile.role==='teacher')await loadStudents()}
function daysSince(date){return Math.max(1,Math.floor((Date.now()-new Date(date+'T00:00:00').getTime())/86400000)+1)}
function progress(p){if(!p||!p.target_date)return 35;var total=new Date(p.target_date)-new Date(p.start_date);if(total<=0)return 100;return Math.max(3,Math.min(100,Math.round((Date.now()-new Date(p.start_date))/total*100)))}
async function render(){document.getElementById('studentView').classList.toggle('hidden',state.classMode);classEl.classList.toggle('hidden',!state.classMode);document.querySelectorAll('[data-view]').forEach(function(b){var on=(b.dataset.view==='class')===state.classMode;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});var mineTab=document.querySelector('[data-view="mine"] .label');if(mineTab)mineTab.textContent=state.profile.role==='teacher'?'관찰일지 보기':'내 관찰일지';document.getElementById('newEntryTop').classList.toggle('hidden',state.classMode||!editable());if(state.classMode)await renderClassV2(false);else{renderSide();renderMain()}}
document.querySelectorAll('[data-view]').forEach(function(b){b.onclick=async function(){var next=b.dataset.view==='class';if(next===state.classMode)return;state.classMode=next;if(!next&&state.profile&&state.profile.role==='student'&&state.current&&!state.current.can_edit){var mine=state.projects.find(function(p){return p.can_edit});if(mine){state.current=mine;await loadEntries()}}await render();window.scrollTo(0,0)}});
document.getElementById('newProjectTop').onclick=function(){prepareProjectDialog()};
function projectOptions(p){var opt=function(x){return '<option value="'+esc(x.id)+'" '+(x.id===p.id?'selected':'')+'>'+(x.grow_type==='group'?'👥 ':'🌱 ')+esc(projectOwnerLabel(x))+' · '+esc(x.plant_name)+'</option>'};if(state.profile.role==='teacher')return state.projects.map(opt).join('');var mine=state.projects.filter(function(x){return x.can_edit}),others=state.projects.filter(function(x){return !x.can_edit});return (mine.length?'<optgroup label="내 관찰일지">'+mine.map(opt).join('')+'</optgroup>':'')+(others.length?'<optgroup label="친구들 관찰일지 (보기만)">'+others.map(opt).join('')+'</optgroup>':'')}
function accessNote(){var p=state.current,members=projectMembers(p);if(!editable())return '<div class="readonly">🔒 '+(p.grow_type==='group'?'다른 모둠의 관찰일지는 볼 수만 있고 수정할 수 없어요.':'다른 친구의 관찰일지는 볼 수만 있고 수정할 수 없어요.')+'</div>';if(p.grow_type==='group')return '<div class="group-note">👥 <b>'+esc(p.group_name||'모둠')+'</b> 모둠원('+members.map(esc).join(', ')+')이 함께 기록하고 고칠 수 있어요.</div>';return ''}

function renderSide(){if(!state.current){side.innerHTML='<div class="side-empty"><div><div style="font-size:54px">🌱</div><b>아직 등록된 식물이 없어요</b><p>'+(state.profile.role==='teacher'?'학생 계정을 만들고 관찰을 시작해 보세요.':'선생님이 계정을 만든 뒤 내 식물을 등록할 수 있어요.')+'</p></div></div>';return}var p=state.current,pct=progress(p);side.innerHTML='<div class="side-top"><div><p class="side-label">선택한 식물</p><h2 class="plant-title">'+esc(p.plant_name)+'</h2><select id="projectPicker" class="project-picker" aria-label="식물 선택">'+projectOptions(p)+'</select></div><div class="plant-art">🌿</div></div><div><div class="progress-head"><span>기른 지 '+daysSince(p.start_date)+'일째</span><span>'+pct+'%</span></div><div class="progress"><i style="width:'+pct+'%"></i></div></div><div class="side-grid"><div class="side-stat">☀️ <span class="side-label">장소</span><b>'+esc(p.growing_location||'아직 미정')+'</b></div><div class="side-stat">🧑‍🌾 <span class="side-label">기르는 사람</span><b>'+esc(p.grow_type==='group'?(p.group_name||p.owner_name)+' ('+projectMembers(p).join(', ')+')':p.owner_name)+'</b></div></div>'+(state.profile.role==='student'?'<button id="addProjectSide" class="btn ghost small" style="width:100%;margin-top:16px;color:white;background:rgba(255,255,255,.1);border-color:rgba(255,255,255,.3)">＋ 새 관찰일지 등록</button>':'');document.getElementById('projectPicker').onchange=async function(e){state.current=state.projects.find(function(x){return x.id===e.target.value});await loadEntries();render()};var add=document.getElementById('addProjectSide');if(add)add.onclick=function(){prepareProjectDialog()}}
function stageTitle(){return state.stage==='before'?'건강하게 자랄 준비를 해요':state.stage==='after'?'성장을 돌아보고 마무리해요':'오늘은 어떤 모습인가요?'}
function renderMain(){if(!state.current){main.innerHTML='<section class="card welcome"><div class="welcome-copy"><p class="eyebrow">나만의 작은 텃밭</p><h1>어떤 식물을<br>길러 볼까요?</h1><p>준비부터 수확까지 사진과 글로 차곡차곡 기록해요.</p><div class="steps"><div class="step">🧤<b>키우기 전</b><small>준비와 다짐</small></div><div class="step">📷<b>키우는 중</b><small>사진과 관찰</small></div><div class="step">🥕<b>키운 후</b><small>수확과 성찰</small></div></div>'+(state.profile.role==='student'?'<button id="firstProject" class="btn">＋ 내 관찰일지 등록하기</button>':'')+'</div><div class="welcome-art">🌻</div></section>';var first=document.getElementById('firstProject');if(first)first.onclick=function(){prepareProjectDialog()};return}main.innerHTML='<p class="eyebrow">'+esc(projectOwnerLabel(state.current))+'의 '+esc(state.current.plant_name)+' 성장 기록</p><h1>'+stageTitle()+'</h1>'+accessNote()+'<div class="stage-tabs"><button class="stage-tab '+(state.stage==='before'?'active':'')+'" data-stage="before">키우기 전</button><button class="stage-tab '+(state.stage==='during'?'active':'')+'" data-stage="during">키우는 중</button><button class="stage-tab '+(state.stage==='after'?'active':'')+'" data-stage="after">키운 후</button></div><div id="stageBody"></div>';document.querySelectorAll('[data-stage]').forEach(function(b){b.onclick=function(){state.stage=b.dataset.stage;renderMain()}});if(state.stage==='before')renderBefore();else if(state.stage==='after')renderAfter();else renderDuring()}
function setFormReadonly(form){if(editable())return;form.querySelectorAll('input,textarea,select,button').forEach(function(el){el.disabled=true})}
function renderBefore(){var p=state.current,b=document.getElementById('stageBody');b.innerHTML='<div class="tip">💡 준비물, 환경, 잘 자라는 시기와 마음가짐을 먼저 정리해요.</div><form id="beforeForm" class="card card-pad"><h2 class="section-title">준비와 계획</h2><div class="form-grid"><label class="field full"><span>필요한 준비물</span><textarea name="supplies">'+esc(p.supplies)+'</textarea></label><label class="field"><span>잘 자라는 시기</span><input name="seasonNote" value="'+esc(p.season_note)+'"></label><label class="field"><span>기르는 장소와 까닭</span><input name="environmentNote" value="'+esc(p.environment_note)+'"></label><label class="field full"><span>나의 마음가짐</span><textarea name="commitment">'+esc(p.commitment)+'</textarea></label></div><div class="save-row"><button class="btn" type="submit">준비 내용 저장</button></div></form>';var f=document.getElementById('beforeForm');setFormReadonly(f);f.onsubmit=function(e){e.preventDefault();saveProject(new FormData(f),'준비 내용을 저장했어요.')}}
function renderAfter(){var p=state.current,b=document.getElementById('stageBody');b.innerHTML='<form id="afterForm" class="card card-pad"><h2 class="section-title">수확과 성찰</h2><div class="form-grid"><label class="field full"><span>수확한 식물을 어떻게 활용했나요?</span><textarea name="harvestUse">'+esc(p.harvest_use)+'</textarea></label><label class="field full"><span>기르며 생긴 문제와 해결 방법</span><textarea name="problems">'+esc(p.problems)+'</textarea></label><label class="field full"><span>기르며 느낀 점</span><textarea name="reflection">'+esc(p.reflection)+'</textarea></label><label class="field full"><span>다음에 다시 기른다면</span><textarea name="nextTime">'+esc(p.next_time)+'</textarea></label></div><div class="save-row"><button class="btn" type="submit">마무리 내용 저장</button></div></form>';var f=document.getElementById('afterForm');setFormReadonly(f);f.onsubmit=function(e){e.preventDefault();saveProject(new FormData(f),'마무리 내용을 저장했어요.')}}
function renderDuring(){var b=document.getElementById('stageBody');b.innerHTML=(editable()?'<button id="addObservation" class="add-observation"><span class="camera-box">📷</span><span class="add-copy"><strong>오늘의 모습을 남겨요</strong><span>사진을 찍고, 달라진 점을 관찰해 보세요.</span><b>새 관찰 기록 쓰기</b></span></button>':'')+'<div id="timeline" class="timeline"></div>';var add=document.getElementById('addObservation');if(add)add.onclick=function(){prepareEntryDialog()};var t=document.getElementById('timeline');if(!state.entries.length){t.innerHTML='<div class="card empty" style="grid-column:1/-1">아직 관찰 기록이 없어요.</div>';return}t.innerHTML=state.entries.map(function(o){var photo=o.photo_key?'<img class="obs-photo" src="/api/photos/'+encodeURIComponent(o.photo_key)+'" alt="관찰 사진" loading="lazy">':'<div class="obs-photo">🌱</div>';var m=(o.height_cm!=null?'<span class="chip">키 '+esc(o.height_cm)+'cm</span>':'')+(o.leaf_count!=null?'<span class="chip">잎 '+esc(o.leaf_count)+'장</span>':'');return '<article class="card obs-card">'+photo+'<div class="obs-body"><div class="obs-meta"><span>'+esc(o.observed_at)+'</span><span>'+esc(o.weather)+'</span></div><h3>'+esc(o.title)+'</h3><p>'+esc(o.note)+'</p>'+(o.changes?'<p style="margin-top:9px"><b>달라진 점</b> '+esc(o.changes)+'</p>':'')+(m?'<div class="measure">'+m+'</div>':'')+(editable()?'<div class="obs-actions"><button class="btn ghost small" type="button" data-edit-entry="'+esc(o.id)+'">✏️ 고치기</button><button class="btn danger small" type="button" data-delete-entry="'+esc(o.id)+'">삭제</button></div>':'')+'</div></article>'}).join('');t.querySelectorAll('[data-edit-entry]').forEach(function(b){b.onclick=function(){prepareEntryDialog(b.dataset.editEntry)}});t.querySelectorAll('[data-delete-entry]').forEach(function(b){b.onclick=function(){deleteEntry(b.dataset.deleteEntry)}})}
async function saveProject(fd,message){if(!editable())return;var payload={};fd.forEach(function(v,k){payload[k]=v});try{var data=await api('/api/projects/'+encodeURIComponent(state.current.id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});var merged=Object.assign({},state.current,data.project);state.current=merged;state.projects=state.projects.map(function(p){return p.id===merged.id?merged:p});toast(message);render()}catch(err){toast(err.message)}}
function myGroups(){var me=state.profile&&state.profile.name,seen={},list=[];state.projects.forEach(function(p){if(p.grow_type!=='group')return;var members=projectMembers(p);if(members.indexOf(me)<0)return;var key=(p.group_name||'')+'|'+members.slice().sort().join(',');if(seen[key])return;seen[key]=1;list.push({name:p.group_name||'모둠',members:members})});return list}
function syncGrowMode(){var f=document.getElementById('projectForm'),group=f.growType.value==='group',sel=document.getElementById('existingGroup'),g=group&&sel.value!==''&&state.groupChoices?state.groupChoices[sel.value]:null;document.getElementById('groupFields').classList.toggle('hidden',!group);document.getElementById('ownerNameField').classList.toggle('hidden',group);document.getElementById('existingGroupField').classList.toggle('hidden',!group||sel.options.length<2);document.getElementById('newGroupFields').classList.toggle('hidden',!!g);var info=document.getElementById('existingGroupInfo');info.textContent=g?'함께 기르는 모둠원: '+g.members.join(', ')+' — 처음 등록한 모둠원과 계속 함께 기르니 이름을 다시 적지 않아도 돼요.':'';info.classList.toggle('hidden',!g);f.ownerName.required=!group;f.groupName.required=group&&!g;f.memberNames.required=group&&!g}
document.getElementById('existingGroup').onchange=syncGrowMode;
document.querySelectorAll('input[name="growType"]').forEach(function(r){r.onchange=syncGrowMode});
function prepareProjectDialog(){if(state.profile.role!=='student')return;var f=document.getElementById('projectForm');f.reset();var groups=myGroups(),sel=document.getElementById('existingGroup');state.groupChoices={};sel.innerHTML=groups.map(function(g,i){state.groupChoices[String(i)]=g;return '<option value="'+i+'">'+esc(g.name)+' ('+esc(g.members.join(', '))+')</option>'}).join('')+'<option value="">＋ 새 모둠 만들기</option>';sel.value=groups.length?'0':'';f.ownerName.value=state.profile.name;f.startDate.value=today();syncGrowMode();openDialog('projectDialog')}
document.getElementById('projectForm').onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.currentTarget),p={};fd.forEach(function(v,k){p[k]=v});var gsel=document.getElementById('existingGroup'),g=p.growType==='group'&&gsel.value!==''&&state.groupChoices?state.groupChoices[gsel.value]:null;if(g){p.groupName=g.name;p.memberNames=g.members.join(',')}var btn=e.submitter;btn.disabled=true;try{var d=await api('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});d.project.observation_count=0;state.projects.unshift(d.project);state.current=d.project;state.entries=[];state.stage='before';state.classMode=false;closeDialog('projectDialog');toast('관찰일지를 만들었어요! 키우기 전 준비부터 적어 보세요.');render()}catch(err){toast(err.message)}finally{btn.disabled=false}};
async function shrinkPhoto(file){if(file.size<=1500000||!window.createImageBitmap)return file;try{var bmp=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bmp.width,bmp.height)),c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);var blob=await new Promise(function(r){c.toBlob(r,'image/jpeg',0.82)});if(!blob||blob.size>=file.size)return file;return new File([blob],String(file.name||'photo').replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'})}catch(e){return file}}
function entrySort(a,b){if(a.observed_at!==b.observed_at)return a.observed_at<b.observed_at?1:-1;return a.created_at<b.created_at?1:-1}
function touchProject(){api('/api/projects').then(function(d){var cur=state.current&&state.current.id;state.projects=d.projects||[];state.current=state.projects.find(function(p){return p.id===cur})||state.current}).catch(function(){})}
function prepareEntryDialog(id){if(!editable())return;var entry=typeof id==='string'?state.entries.find(function(o){return o.id===id}):null,f=document.getElementById('entryForm'),el=function(n){return f.elements.namedItem(n)},img=document.getElementById('photoPreview');state.editingEntry=entry||null;f.reset();document.getElementById('entryDialogTitle').textContent=entry?'관찰 기록 고치기':'오늘의 관찰 기록';document.getElementById('entrySubmit').textContent=entry?'고친 내용 저장하기':'관찰 기록 저장하기';document.getElementById('removePhotoField').classList.toggle('hidden',!(entry&&entry.photo_key));img.style.display='none';if(entry){el('observedAt').value=entry.observed_at;el('weather').value=entry.weather||'맑음';el('title').value=entry.title;el('note').value=entry.note;el('changes').value=entry.changes||'';el('heightCm').value=entry.height_cm==null?'':entry.height_cm;el('leafCount').value=entry.leaf_count==null?'':entry.leaf_count;if(entry.photo_key){img.src='/api/photos/'+encodeURIComponent(entry.photo_key);img.style.display='block'}}else el('observedAt').value=today();openDialog('entryDialog')}
async function deleteEntry(id){if(!editable()||!confirm('이 관찰 기록을 삭제할까요? 삭제하면 되돌릴 수 없어요.'))return;try{await api('/api/observations/'+encodeURIComponent(id),{method:'DELETE'});state.entries=state.entries.filter(function(o){return o.id!==id});toast('관찰 기록을 삭제했어요.');touchProject();renderMain()}catch(err){toast(err.message)}}
document.getElementById('entryForm').onsubmit=async function(e){e.preventDefault();if(!editable())return;var fd=new FormData(e.currentTarget);fd.set('projectId',state.current.id);var file=fd.get('photo');if(file&&file.size){file=await shrinkPhoto(file);fd.set('photo',file,file.name)}if(file&&file.size>4*1024*1024){toast('사진이 너무 커요. 4MB보다 작은 사진을 골라 주세요.');return}var btn=e.submitter,editing=state.editingEntry;btn.disabled=true;try{if(editing){var u=await api('/api/observations/'+encodeURIComponent(editing.id),{method:'PATCH',body:fd});state.entries=state.entries.map(function(o){return o.id===u.observation.id?u.observation:o})}else{var d=await api('/api/observations',{method:'POST',body:fd});state.entries.unshift(d.observation)}state.entries.sort(entrySort);state.editingEntry=null;closeDialog('entryDialog');toast(editing?'관찰 기록을 고쳤어요.':'오늘의 관찰 기록을 저장했어요!');touchProject();renderMain()}catch(err){toast(err.message)}finally{btn.disabled=false}};
document.getElementById('newEntryTop').onclick=function(){prepareEntryDialog()};

async function loadStudents(){if(state.profile.role!=='teacher')return;var d=await api('/api/admin/students');state.students=d.students||[]}
async function renderClass(){if(state.profile.role==='teacher')try{await loadStudents()}catch(err){toast(err.message)}var admin=state.profile.role==='teacher'?'<section class="card admin-panel"><h2 class="section-title">학생 계정 관리</h2><p class="section-help">학생 이름을 등록하면 초기 비밀번호는 0000입니다.</p><form id="addStudentForm" class="admin-grid"><label class="field"><span>학생 이름</span><input name="name" required maxlength="30" placeholder="예: 김민지"></label><button class="btn" type="submit">학생 추가</button></form><div style="margin-top:15px">'+(state.students.length?state.students.map(function(s){return '<div class="account-row"><div><b>'+esc(s.name)+'</b><br><small>'+(s.must_change_pin?'초기 비밀번호 사용 중':'개인 비밀번호 설정 완료')+'</small></div><span class="status">'+(s.locked_until?'잠금':'사용 가능')+'</span><button class="btn danger small" data-reset="'+esc(s.id)+'">0000으로 초기화</button></div>'}).join(''):'<div class="empty">등록된 학생 계정이 없어요.</div>')+'</div></section>':'';classEl.innerHTML=admin+'<div class="class-head"><div><p class="eyebrow">'+esc(state.profile.class_code)+'</p><h1 style="margin:4px 0">우리 반 식물 현황</h1><p style="margin:0;color:var(--muted)">친구들의 기록을 골라 살펴볼 수 있어요.</p></div><button id="refreshClass" class="btn secondary">↻ 새로고침</button></div><div class="student-list">'+(state.projects.length?state.projects.map(function(p){return '<div class="student-row"><div><b>'+esc(p.student_name)+'</b><br><small>'+esc(p.owner_name)+'</small></div><div><b>'+esc(p.plant_name)+'</b><br><small>'+esc(p.growing_location||'장소 미입력')+'</small></div><span class="status">'+daysSince(p.start_date)+'일째</span><button class="btn ghost small" data-open-project="'+esc(p.id)+'">기록 보기</button></div>'}).join(''):'<div class="card empty">아직 등록된 식물이 없어요.</div>')+'</div>';var addForm=document.getElementById('addStudentForm');if(addForm)addForm.onsubmit=addStudent;document.querySelectorAll('[data-reset]').forEach(function(b){b.onclick=function(){resetStudent(b.dataset.reset)}});document.querySelectorAll('[data-open-project]').forEach(function(b){b.onclick=async function(){state.current=state.projects.find(function(p){return p.id===b.dataset.openProject});await loadEntries();state.classMode=false;render()}});document.getElementById('refreshClass').onclick=async function(){await loadProjects();render();toast('학급 현황을 새로 불러왔어요.')}}
async function addStudent(e){e.preventDefault();var form=e.currentTarget,f=new FormData(form),btn=submitButton(e);busy(btn,true,'추가 중…');try{await api('/api/admin/students',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:f.get('name')})});form.reset();await refreshAll();await renderClassV2(false);toast('학생 계정을 만들었어요. 초기 비밀번호는 0000입니다.')}catch(err){toast(err.message)}finally{busy(btn,false)}}
async function normalizeCsvUpload(file){var bytes=await file.arrayBuffer(),view=new Uint8Array(bytes),decoded;if(view[0]===0xFF&&view[1]===0xFE)decoded=new TextDecoder('utf-16le').decode(view.slice(2));else if(view[0]===0xFE&&view[1]===0xFF)decoded=new TextDecoder('utf-16be').decode(view.slice(2));else try{decoded=new TextDecoder('utf-8',{fatal:true}).decode(view)}catch(e){decoded=new TextDecoder('euc-kr').decode(view)}return new File(['\uFEFF'+decoded.replace(/^\uFEFF/,'')],file.name||'student-list.csv',{type:'text/csv;charset=utf-8'})}
async function importStudentCsv(e){e.preventDefault();var form=e.currentTarget,fd=new FormData(form),file=fd.get('file'),btn=submitButton(e);if(!file||!file.size){toast('CSV 파일을 선택해 주세요.');return}busy(btn,true,'명단 읽는 중…');try{fd.set('file',await normalizeCsvUpload(file));var result=await api('/api/admin/students/import',{method:'POST',body:fd});form.reset();await refreshAll();await renderClassV2(false);toast(result.added+'명을 바로 추가했어요.'+(result.skipped?' 중복 '+result.skipped+'명은 건너뛰었어요.':''))}catch(err){toast(err.message)}finally{busy(btn,false)}}
function galleryHtml(){var f=state.galleryFilter||'all',student=state.profile.role==='student',filters=[['all','전체'],['individual','🌱 개인'],['group','👥 모둠']];if(student)filters.push(['mine','✏️ 내 기록']);var match=function(p,k){return k==='all'||(k==='mine'?!!p.can_edit:p.grow_type===k)};var list=state.projects.filter(function(p){return match(p,f)});var bar='<div class="gallery-filters">'+filters.map(function(x){var n=state.projects.filter(function(p){return match(p,x[0])}).length;return '<button type="button" class="filter-chip '+(f===x[0]?'active':'')+'" data-filter="'+x[0]+'">'+x[1]+' <span>'+n+'</span></button>'}).join('')+'</div>';if(!list.length)return bar+'<div class="card empty">'+(state.projects.length?'조건에 맞는 식물이 없어요.':'아직 등록된 식물이 없어요.')+'</div>';return bar+'<div class="plant-grid">'+list.map(function(p){var members=projectMembers(p),group=p.grow_type==='group',count=Number(p.observation_count||0),cover=p.cover_photo_key?'<img src="/api/photos/'+encodeURIComponent(p.cover_photo_key)+'" alt="'+esc(p.plant_name)+' 사진" loading="lazy">':'<span class="plant-tile-emoji">'+(group?'🪴':'🌱')+'</span>',stage=(p.completed_at||p.reflection||p.harvest_use)?'키운 후':count>0?'키우는 중':'키우기 전';return '<button type="button" class="plant-tile" data-open-project="'+esc(p.id)+'"><div class="plant-tile-photo">'+cover+'<span class="tile-badge'+(group?' group':'')+'">'+(group?'👥 모둠':'🌱 개인')+'</span>'+(student&&p.can_edit?'<span class="tile-mine">내 기록</span>':'')+'</div><div class="plant-tile-body"><strong>'+esc(p.plant_name)+'</strong><span class="tile-owner">'+esc(projectOwnerLabel(p))+'</span>'+(group&&members.length?'<span class="tile-members">'+members.map(esc).join(' · ')+'</span>':'')+'<div class="tile-meta"><span>'+daysSince(p.start_date)+'일째</span><span>관찰 '+count+'회</span><span>'+stage+'</span></div></div></button>'}).join('')+'</div>'}
async function renderClassV2(reload){if(reload!==false&&state.profile.role==='teacher')try{await loadStudents()}catch(err){toast(err.message)}var admin=state.profile.role==='teacher'?'<section class="card admin-panel"><div class="admin-title"><div><p class="eyebrow">선생님 관리실</p><h2 class="section-title">학생 계정 관리</h2><p class="section-help">직접 추가하거나 CSV 명단을 올리세요. 엑셀에서 저장한 한글 CSV도 바로 읽을 수 있어요.</p></div><span class="student-count">학생 '+state.students.length+'명</span></div><form id="addStudentForm" class="admin-grid"><label class="field"><span>학생 이름</span><input name="name" required maxlength="30" placeholder="예: 김민지"></label><button class="btn" type="submit">학생 추가</button></form><form id="importStudentForm" class="admin-import"><label class="field"><span>학생 명단 CSV</span><input type="file" name="file" accept=".csv,text/csv" required></label><a class="btn ghost" href="/api/admin/students/template.csv" download="student-list-template.csv">CSV 양식 받기</a><button class="btn" type="submit">명단 일괄 추가</button></form><p class="import-note">첫 줄에는 이름·학생 이름·성명 중 하나를 적어 주세요. 새 학생의 초기 비밀번호는 0000입니다.</p><div class="account-list">'+(state.students.length?state.students.map(function(s){return '<div class="account-row"><div><b>'+esc(s.name)+'</b><br><small>'+(s.must_change_pin?'초기 비밀번호 사용 중':'개인 비밀번호 설정 완료')+'</small></div><span class="status">'+(s.locked_until?'잠금':'사용 가능')+'</span><button class="btn danger small" data-reset="'+esc(s.id)+'">0000으로 초기화</button></div>'}).join(''):'<div class="empty">등록된 학생 계정이 없어요.</div>')+'</div></section>':'';classEl.innerHTML=admin+'<div class="class-head"><div><p class="eyebrow">'+esc(state.profile.class_code)+'의 작은 텃밭</p><h1>우리 반 식물 모음</h1><p>친구들의 식물을 한눈에 구경해요. 카드를 누르면 관찰일지를 볼 수 있어요.</p></div><button id="refreshClass" class="btn secondary">↻ 새로 불러오기</button></div>'+galleryHtml();var addForm=document.getElementById('addStudentForm');if(addForm)addForm.onsubmit=addStudent;var importForm=document.getElementById('importStudentForm');if(importForm)importForm.onsubmit=importStudentCsv;document.querySelectorAll('[data-reset]').forEach(function(b){b.onclick=function(){resetStudent(b.dataset.reset)}});document.querySelectorAll('[data-open-project]').forEach(function(b){b.onclick=async function(){state.current=state.projects.find(function(p){return p.id===b.dataset.openProject});await loadEntries();state.classMode=false;state.stage='during';await render();window.scrollTo(0,0)}});document.querySelectorAll('[data-filter]').forEach(function(b){b.onclick=function(){state.galleryFilter=b.dataset.filter;renderClassV2(false)}});document.getElementById('refreshClass').onclick=async function(e){var btn=e.currentTarget;busy(btn,true,'불러오는 중…');try{await refreshAll();await renderClassV2(false);toast('최신 내용을 불러왔어요.')}finally{busy(btn,false)}}}
async function resetStudent(id){if(!confirm('이 학생의 비밀번호를 0000으로 초기화할까요?'))return;try{await api('/api/admin/students/'+encodeURIComponent(id)+'/reset',{method:'POST'});await loadStudents();await renderClassV2(false);toast('비밀번호를 0000으로 초기화했어요.')}catch(err){toast(err.message)}}
function registerTools(){var ctx=document.modelContext;if(!ctx||!ctx.registerTool||registerTools.done)return;registerTools.done=true;try{ctx.registerTool({name:'list_observations',title:'관찰 기록 보기',description:'선택한 식물의 관찰 기록을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:function(){return {plant:state.current&&state.current.plant_name,observations:state.entries}}});ctx.registerTool({name:'start_observation',title:'관찰 기록 시작',description:'내 식물의 새 관찰 기록 입력창을 엽니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:function(){if(!editable())throw new Error('내 식물 기록에서만 새 관찰을 만들 수 있어요.');prepareEntryDialog();return {status:'ready'}}})}catch(e){console.warn(e)}}
(async function(){try{var r=await fetch('/api/auth/me',{cache:'no-store'}),d=await r.json();if(r.ok)await start(d.account);else showLogin()}catch(e){showLogin()}})();
})();`;
