export const APP_HTML = String.raw`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>우리 반 식물 관찰일지</title><meta name="description" content="식물을 기르며 사진과 관찰 내용을 단계별로 기록하는 학급용 관찰일지">
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%232d7a4a'/%3E%3Ctext x='32' y='44' font-size='38' text-anchor='middle'%3E🌱%3C/text%3E%3C/svg%3E">
<link rel="stylesheet" href="/assets/styles.css?v=10"><script src="/assets/app.js?v=10" defer></script></head>
<body>
<div id="gate" class="gate"><div class="gate-shell"><section class="gate-hello"><span class="gate-badge">우리 반 작은 텃밭</span><div class="gate-garden" aria-hidden="true"><span>🌻</span><span>🌱</span><span>🍅</span></div><h1>오늘도 식물이<br>한 뼘 자랐어요!</h1><p>사진과 글로 매일의 작은 변화를 모아<br>우리 반만의 성장 이야기를 만들어요.</p><div class="gate-steps"><span>① 준비하기</span><span>② 관찰하기</span><span>③ 돌아보기</span></div></section><form id="gateForm" class="gate-card"><div class="gate-mark">🌱</div><p class="gate-kicker">반가워요!</p><h2>관찰일지 들어가기</h2><p>학급 코드, 이름, 네 자리 비밀번호를 입력해 주세요.</p>
<label class="field"><span>학급 코드</span><input name="classCode" maxlength="20" required placeholder="예: HAETSAL-6-2" autocomplete="off"></label>
<label class="field" style="margin-top:14px"><span>이름</span><input name="name" maxlength="30" required placeholder="예: 김민지" autocomplete="username"></label>
<label class="field" style="margin-top:14px"><span>네 자리 비밀번호</span><input class="pin-input" name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="current-password" aria-label="네 자리 비밀번호"></label>
<div class="role-choice"><label><input type="radio" name="role" value="student" checked> 학생</label><label><input type="radio" name="role" value="teacher"> 교사</label></div>
<button class="btn login-btn" style="width:100%" type="submit">로그인</button><p class="gate-note">학생 계정은 선생님이 먼저 만들어 줍니다. 학생 초기 비밀번호는 0000입니다.</p><button id="teacherSignupOpen" class="btn ghost small hidden" type="button" style="width:100%;margin-top:10px">선생님이 처음이신가요? 교사 계정 만들기</button></form></div></div>

<div id="app" class="hidden"><div class="loading-bar" aria-hidden="true"></div><header class="topbar"><div class="topbar-inner"><div class="brand"><span class="brand-mark">🌱</span><div><span class="brand-kicker">우리 반 작은 텃밭</span><strong>식물 관찰일지</strong><small id="profileLine"></small></div></div><div class="header-actions"><button id="newProjectTop" class="btn secondary small hidden"><span>📒</span><span class="label">관찰일지 등록</span></button><button id="newEntryTop" class="btn small"><span>＋</span><span class="label">관찰 기록</span></button><button id="logoutBtn" class="btn ghost small">로그아웃</button></div></div><nav id="viewTabs" class="view-tabs hidden" role="tablist" aria-label="화면 선택"><button class="view-tab active" type="button" role="tab" data-view="mine"><span>🌿</span><span class="label">내 관찰일지</span></button><button class="view-tab" type="button" role="tab" data-view="class"><span>🪴</span><span class="label">우리 반 식물 모음</span></button><button id="adminTab" class="view-tab hidden" type="button" role="tab" data-view="admin"><span>🧑‍🏫</span><span class="label">학생 계정 관리</span></button></nav></header>
<div id="studentView" class="shell"><aside id="side" class="side"></aside><main class="content"><div id="mainContent"></div></main></div>
<main id="classView" class="content hidden" style="max-width:1180px;margin:auto;padding:28px 24px"></main></div>

<dialog id="projectDialog"><div class="dialog-head"><div><h2>내 관찰일지 등록하기</h2><p>혼자(개인) 또는 친구들과(모둠) 기를 식물을 등록해요.</p></div><button class="close" type="button" data-close="projectDialog">✕</button></div><form id="projectForm" class="dialog-body"><div class="form-grid">
<fieldset class="field full mode-field"><legend>기르는 방법</legend><div id="growModeChoice" class="role-choice"><label><input type="radio" name="growType" value="individual" checked> 개인</label><label><input type="radio" name="growType" value="group"> 모둠</label></div></fieldset>
<label class="field"><span>기를 식물</span><input name="plantName" required maxlength="50" placeholder="예: 방울토마토, 바질"></label><label id="ownerNameField" class="field"><span>기르는 사람</span><input name="ownerName" required maxlength="50"></label>
<div id="groupFields" class="field full hidden"><label id="existingGroupField" class="field hidden"><span>함께 기를 모둠</span><select id="existingGroup"></select></label><p id="existingGroupInfo" class="group-info hidden"></p><div id="newGroupFields"><div class="form-grid"><label class="field"><span>모둠 이름</span><input name="groupName" maxlength="50" placeholder="예: 초록 모둠"></label><label class="field"><span>모둠원 이름</span><textarea name="memberNames" maxlength="500" placeholder="한 줄에 한 명씩 또는 쉼표로 입력하세요.&#10;예: 김민지, 이준호, 박서윤"></textarea></label></div><p class="gate-note">학생 계정의 이름과 똑같이 입력하세요. 등록한 모둠원은 모두 이 관찰일지를 함께 수정할 수 있어요. 처음 한 번만 적으면 이후에는 모둠원을 다시 적지 않아도 계속 함께 기록할 수 있어요.</p></div></div>
<label class="field"><span>시작한 날</span><input type="date" name="startDate" required></label><label class="field"><span>예상 마치는 날</span><input type="date" name="targetDate"></label><label class="field full"><span>기르는 장소</span><input name="growingLocation" maxlength="100" placeholder="예: 교실 남쪽 창가"></label></div><div class="save-row"><button class="btn" type="submit">관찰일지 만들기</button></div></form></dialog>

<dialog id="entryDialog"><div class="dialog-head"><div><h2 id="entryDialogTitle">오늘의 관찰 기록</h2><p>사진과 함께 눈에 띈 변화를 적어 보세요.</p></div><button class="close" type="button" data-close="entryDialog">✕</button></div><form id="entryForm" class="dialog-body"><div class="form-grid"><label class="field"><span>관찰한 날</span><input type="date" name="observedAt" required></label><label class="field"><span>날씨</span><select name="weather"><option>맑음</option><option>흐림</option><option>비</option><option>눈</option><option>기타</option></select></label><label class="field full"><span>관찰 제목</span><input name="title" required maxlength="100" placeholder="예: 씨앗을 심었어요"></label><label class="field full"><span>관찰한 모습</span><textarea name="note" required maxlength="1500" placeholder="씨앗을 흙에 심고 물을 주었다."></textarea></label><label class="field full"><span>지난번과 달라진 점</span><textarea name="changes" maxlength="1000" placeholder="키나 잎 수가 어떻게 달라졌는지 적어 보세요."></textarea></label><label class="field"><span>키 (cm, 선택)</span><input type="number" step="0.1" min="0" max="1000" name="heightCm"></label><label class="field"><span>잎 수 (선택)</span><input type="number" step="1" min="0" max="10000" name="leafCount"></label><label class="field full"><span>식물 사진 (선택 · 큰 사진은 자동으로 줄여서 올려요)</span><input id="photoInput" type="file" name="photo" accept="image/*" capture="environment"><img id="photoPreview" class="preview-photo" alt="선택한 사진 미리보기"></label><label id="removePhotoField" class="check-line full hidden"><input type="checkbox" name="removePhoto" value="1"> 기존 사진 지우기</label></div><div class="save-row"><button id="entrySubmit" class="btn" type="submit">관찰 기록 저장하기</button></div></form></dialog>

<dialog id="teacherSignupDialog"><div class="dialog-head"><div><h2>교사 계정 만들기</h2><p>학급마다 선생님 계정은 한 개만 만들 수 있어요.</p></div><button class="close" type="button" data-close="teacherSignupDialog">✕</button></div><form id="teacherSignupForm" class="dialog-body"><div class="form-grid"><label class="field"><span>학급 코드</span><input name="classCode" maxlength="20" required placeholder="예: HAETSAL-6-2" autocomplete="off"></label><label class="field"><span>이름</span><input name="name" maxlength="30" required placeholder="예: 김선생" autocomplete="username"></label><label class="field full"><span>교사 가입 코드</span><input name="signupCode" type="password" maxlength="100" required autocomplete="off"></label><label class="field"><span>사용할 비밀번호 (숫자 네 자리)</span><input class="pin-input" name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="new-password"></label><label class="field"><span>비밀번호 확인</span><input class="pin-input" name="confirmPin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="new-password"></label></div><p class="gate-note">교사 가입 코드는 사이트 관리자만 알고 있는 코드예요. 학생에게 알려 주지 마세요.</p><div class="save-row"><button class="btn" type="submit">교사 계정 만들기</button></div></form></dialog>
<dialog id="changePinDialog"><div class="dialog-head"><div><h2>비밀번호 바꾸기</h2><p>나만 아는 네 자리 숫자를 정해 주세요.</p></div></div><form id="changePinForm" class="dialog-body"><div class="form-grid"><label class="field full"><span>현재 비밀번호</span><input class="pin-input" name="currentPin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label><label class="field"><span>새 비밀번호</span><input class="pin-input" name="newPin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label><label class="field"><span>새 비밀번호 확인</span><input class="pin-input" name="confirmPin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label></div><div class="save-row"><button class="btn" type="submit">새 비밀번호 저장</button></div></form></dialog>
<div id="toast" class="toast hidden" role="status" aria-live="polite"></div></body></html>`;
