import { APP_HTML } from './html.js';
import { APP_CSS } from './styles.js';
import { APP_JS } from './client.js';

const COOKIE='plant_session', SESSION_SECONDS=7*24*60*60, MAX_PHOTO=8*1024*1024, PBKDF2_ITERATIONS=100000;
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const text=function(v){return String(v==null?'':v).trim()};
const json=function(data,status,headers){return new Response(JSON.stringify(data),{status:status||200,headers:Object.assign({},JSON_HEADERS,headers||{})})};
const fail=function(message,status){return json({error:message},status||400)};
const cleanClass=function(v){return text(v).toUpperCase().replace(/[^A-Z0-9가-힣_-]/g,'').slice(0,20)};
const cleanName=function(v){return text(v).replace(/[<>]/g,'').slice(0,30)};
const isPin=function(v){return /^\d{4}$/.test(String(v||''))};
function parseMemberNames(value){var source=Array.isArray(value)?value.join(','):text(value);if(source.startsWith('[')){try{var parsed=JSON.parse(source);if(Array.isArray(parsed))source=parsed.join(',')}catch(e){}}var seen=new Set(),names=[];source.split(/[,;\n\r]+/).forEach(function(v){var name=cleanName(v);if(name&&!seen.has(name)&&names.length<20){seen.add(name);names.push(name)}});return names}
function csvDelimiter(value){var first=String(value||'').replace(/^\uFEFF/,'').split(/\r?\n/).find(function(line){return text(line)!==''})||'',choices=[',',';','\t'],best=',',count=-1;choices.forEach(function(d){var n=first.split(d).length-1;if(n>count){best=d;count=n}});return best}
function csvRows(value,delimiter){var rows=[],row=[],cell='',quoted=false;value=String(value||'').replace(/^\uFEFF/,'');delimiter=delimiter||csvDelimiter(value);for(var i=0;i<value.length;i++){var c=value[i];if(quoted){if(c==='"'&&value[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===delimiter){row.push(cell);cell=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&value[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(function(x){return text(x)!==''}))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(function(x){return text(x)!==''}))rows.push(row);return rows}
function normalizeHeader(value){return text(value).replace(/[\s_\-]+/g,'').toLowerCase()}
async function csvText(file){var bytes=new Uint8Array(await file.arrayBuffer());if(bytes[0]===0xFF&&bytes[1]===0xFE)return new TextDecoder('utf-16le').decode(bytes.subarray(2));if(bytes[0]===0xFE&&bytes[1]===0xFF)return new TextDecoder('utf-16be').decode(bytes.subarray(2));try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch(e){try{return new TextDecoder('euc-kr',{fatal:true}).decode(bytes)}catch(ignore){return new TextDecoder('utf-8').decode(bytes)}}}

function bytesToB64(bytes){var s='';for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64ToBytes(value){var s=value.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';var raw=atob(s),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function sha(value){return bytesToB64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))))}
async function hashPin(pin,salt){var key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);var bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64ToBytes(salt),iterations:PBKDF2_ITERATIONS},key,256);return bytesToB64(new Uint8Array(bits))}
async function newPinHash(pin){var salt=bytesToB64(crypto.getRandomValues(new Uint8Array(16)));return {salt:salt,hash:await hashPin(pin,salt)}}
function randomToken(){return bytesToB64(crypto.getRandomValues(new Uint8Array(32)))}
function cookieValue(request){var raw=request.headers.get('cookie')||'',parts=raw.split(';');for(var i=0;i<parts.length;i++){var p=parts[i].trim(),at=p.indexOf('=');if(at>0&&p.slice(0,at)===COOKIE)return p.slice(at+1)}return ''}
function sessionCookie(token,maxAge){return COOKIE+'='+token+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+maxAge}
function publicAccount(row){return {id:row.id,class_code:row.class_code,name:row.name,role:row.role,must_change_pin:!!row.must_change_pin}}

async function getSession(request,env){var token=cookieValue(request);if(!token)return null;var tokenHash=await sha(token),now=new Date().toISOString();var row=await env.DB.prepare('SELECT a.*,s.id AS session_id,s.expires_at FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.expires_at>?').bind(tokenHash,now).first();return row||null}
async function issueSession(accountId,env){var token=randomToken(),tokenHash=await sha(token),now=new Date(),expires=new Date(now.getTime()+SESSION_SECONDS*1000).toISOString();await env.DB.prepare('INSERT INTO sessions (id,account_id,token_hash,expires_at,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),accountId,tokenHash,expires,now.toISOString()).run();return token}
async function requireSession(request,env,allowChange){var session=await getSession(request,env);if(!session)return {error:fail('로그인이 필요해요.',401)};if(session.must_change_pin&&!allowChange)return {error:fail('먼저 비밀번호를 변경해 주세요.',403)};return {session:session}}

async function login(request,env){var body=await request.json(),code=cleanClass(body.classCode),name=cleanName(body.name),role=body.role==='teacher'?'teacher':'student',pin=String(body.pin||'');if(!code||!name||!isPin(pin))return fail('학급 코드, 이름, 네 자리 비밀번호를 확인해 주세요.');var row=await env.DB.prepare('SELECT * FROM accounts WHERE class_code=? AND name=? AND role=?').bind(code,name,role).first();
 if(!row)return fail(role==='student'?'선생님이 먼저 학생 계정을 만들어 주세요.':'로그인 정보를 확인해 주세요. 처음이라면 ‘교사 계정 만들기’를 눌러 주세요.',401);
 var nowMs=Date.now();if(row.locked_until&&new Date(row.locked_until).getTime()>nowMs)return fail('비밀번호를 여러 번 틀렸어요. 10분 뒤 다시 시도해 주세요.',423);var valid=(await hashPin(pin,row.pin_salt))===row.pin_hash;if(!valid){var attempts=Number(row.failed_attempts||0)+1,locked=attempts>=5?new Date(nowMs+10*60*1000).toISOString():null;await env.DB.prepare('UPDATE accounts SET failed_attempts=?,locked_until=?,updated_at=? WHERE id=?').bind(attempts>=5?0:attempts,locked,new Date().toISOString(),row.id).run();return fail('로그인 정보를 확인해 주세요.',401)}
 await env.DB.prepare('UPDATE accounts SET failed_attempts=0,locked_until=NULL,updated_at=? WHERE id=?').bind(new Date().toISOString(),row.id).run();var token=await issueSession(row.id,env);return json({account:publicAccount(row)},200,{'set-cookie':sessionCookie(token,SESSION_SECONDS)})}
async function teacherSignup(request,env){var expected=text(env.TEACHER_SIGNUP_CODE);if(!expected)return fail('교사 가입이 아직 준비되지 않았어요. 사이트 관리자에게 문의해 주세요.',503);var body=await request.json(),code=cleanClass(body.classCode),name=cleanName(body.name),pin=String(body.pin||''),signup=text(body.signupCode);if(!code||!name||!isPin(pin))return fail('학급 코드, 이름, 네 자리 비밀번호를 확인해 주세요.');if(!signup||(await sha(signup))!==(await sha(expected)))return fail('교사 가입 코드가 맞지 않아요.',403);var existing=await env.DB.prepare("SELECT id FROM accounts WHERE class_code=? AND role='teacher'").bind(code).first();if(existing)return fail('이미 선생님이 등록된 학급 코드예요. 로그인해 주세요.',409);var ph=await newPinHash(pin),id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO accounts (id,class_code,name,role,pin_salt,pin_hash,must_change_pin,created_at,updated_at) VALUES (?,?,?,'teacher',?,?,0,?,?)").bind(id,code,name,ph.salt,ph.hash,now,now).run();var row=await env.DB.prepare('SELECT * FROM accounts WHERE id=?').bind(id).first(),token=await issueSession(id,env);return json({account:publicAccount(row)},201,{'set-cookie':sessionCookie(token,SESSION_SECONDS)})}
async function me(request,env){var s=await getSession(request,env);return s?json({account:publicAccount(s)}):fail('로그인이 필요해요.',401)}
async function logout(request,env){var token=cookieValue(request);if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(token)).run();return json({ok:true},200,{'set-cookie':sessionCookie('',0)})}
async function changePin(request,env,session){var body=await request.json(),current=String(body.currentPin||''),next=String(body.newPin||'');if(!isPin(current)||!isPin(next))return fail('네 자리 숫자를 입력해 주세요.');if((await hashPin(current,session.pin_salt))!==session.pin_hash)return fail('현재 비밀번호가 맞지 않아요.',401);var ph=await newPinHash(next),now=new Date().toISOString();await env.DB.prepare('UPDATE accounts SET pin_salt=?,pin_hash=?,must_change_pin=0,failed_attempts=0,locked_until=NULL,updated_at=? WHERE id=?').bind(ph.salt,ph.hash,now,session.id).run();await env.DB.prepare('DELETE FROM sessions WHERE account_id=?').bind(session.id).run();var token=await issueSession(session.id,env),row=await env.DB.prepare('SELECT * FROM accounts WHERE id=?').bind(session.id).first();return json({account:publicAccount(row)},200,{'set-cookie':sessionCookie(token,SESSION_SECONDS)})}

function canEdit(session,project){if(session.role==='teacher'||project.student_name===session.name)return true;if(project.grow_type!=='group')return false;return parseMemberNames(project.member_names).includes(session.name)}
async function projectForClass(id,session,env){return env.DB.prepare('SELECT * FROM projects WHERE id=? AND class_code=?').bind(id,session.class_code).first()}
async function listProjects(session,env){var result=await env.DB.prepare('SELECT p.*,(SELECT COUNT(*) FROM observations o WHERE o.project_id=p.id) AS observation_count,(SELECT MAX(o.observed_at) FROM observations o WHERE o.project_id=p.id) AS last_observed_at,(SELECT o.photo_key FROM observations o WHERE o.project_id=p.id AND o.photo_key IS NOT NULL ORDER BY o.observed_at DESC,o.created_at DESC LIMIT 1) AS cover_photo_key FROM projects p WHERE p.class_code=? ORDER BY p.updated_at DESC').bind(session.class_code).all();return json({projects:(result.results||[]).map(function(p){p.can_edit=canEdit(session,p);return p})})}
async function createProject(request,session,env){
 if(session.role!=='student')return fail('학생 계정에서 식물 기록을 만들어 주세요.',403);
 var b=await request.json(),plant=text(b.plantName).slice(0,50),start=text(b.startDate),growType=b.growType==='group'?'group':'individual',groupName=growType==='group'?text(b.groupName).slice(0,50):'',members=growType==='group'?parseMemberNames(b.memberNames):[];
 if(growType==='group'&&!members.includes(session.name))members.unshift(session.name);members=members.slice(0,20);
 var owner=growType==='group'?groupName:text(b.ownerName).slice(0,50);
 if(!plant||!owner||!start)return fail(growType==='group'?'식물, 모둠 이름, 시작한 날을 모두 입력해 주세요.':'식물, 기르는 사람, 시작한 날을 모두 입력해 주세요.');
 if(growType==='group'&&members.length<2)return fail('모둠원 이름을 한 명 이상 더 입력해 주세요.');
 if(growType==='group'){var accounts=await env.DB.prepare("SELECT name FROM accounts WHERE class_code=? AND role='student'").bind(session.class_code).all(),registered=new Set((accounts.results||[]).map(function(x){return x.name})),missing=members.filter(function(name){return !registered.has(name)});if(missing.length)return fail('학생 계정에 없는 이름이 있어요: '+missing.join(', '));}
 var id=crypto.randomUUID(),now=new Date().toISOString();
 await env.DB.prepare('INSERT INTO projects (id,class_code,student_name,plant_name,owner_name,grow_type,group_name,member_names,start_date,target_date,growing_location,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,session.class_code,session.name,plant,owner,growType,groupName,JSON.stringify(members),start,text(b.targetDate)||null,text(b.growingLocation).slice(0,100),now,now).run();
 var row=await projectForClass(id,session,env);row.can_edit=true;return json({project:row},201)
}
async function updateProject(request,session,env,id){var project=await projectForClass(id,session,env);if(!project)return fail('식물 기록을 찾을 수 없어요.',404);if(!canEdit(session,project))return fail('다른 친구의 관찰일지는 수정할 수 없어요.',403);var b=await request.json(),keys=['supplies','seasonNote','environmentNote','commitment','harvestUse','problems','reflection','nextTime'],v={};keys.forEach(function(k){v[k]=b[k]===undefined?null:text(b[k]).slice(0,3000)});await env.DB.prepare('UPDATE projects SET supplies=COALESCE(?,supplies),season_note=COALESCE(?,season_note),environment_note=COALESCE(?,environment_note),commitment=COALESCE(?,commitment),harvest_use=COALESCE(?,harvest_use),problems=COALESCE(?,problems),reflection=COALESCE(?,reflection),next_time=COALESCE(?,next_time),updated_at=? WHERE id=?').bind(v.supplies,v.seasonNote,v.environmentNote,v.commitment,v.harvestUse,v.problems,v.reflection,v.nextTime,new Date().toISOString(),id).run();var row=await projectForClass(id,session,env);row.can_edit=true;return json({project:row})}
async function listObservations(url,session,env){var id=text(url.searchParams.get('projectId')),project=await projectForClass(id,session,env);if(!project)return fail('식물 기록을 찾을 수 없어요.',404);var result=await env.DB.prepare('SELECT * FROM observations WHERE project_id=? ORDER BY observed_at DESC,created_at DESC').bind(id).all();return json({observations:result.results||[]})}
async function createObservation(request,session,env){var type=request.headers.get('content-type')||'',b,photo;if(type.includes('multipart/form-data')){var form=await request.formData();b=Object.fromEntries(form.entries());photo=form.get('photo')}else b=await request.json();var projectId=text(b.projectId),project=await projectForClass(projectId,session,env);if(!project)return fail('식물 기록을 찾을 수 없어요.',404);if(!canEdit(session,project))return fail('다른 친구의 관찰일지는 수정할 수 없어요.',403);var observed=text(b.observedAt),title=text(b.title).slice(0,100),note=text(b.note).slice(0,1500);if(!observed||!title||!note)return fail('날짜, 제목, 관찰한 모습을 모두 입력해 주세요.');var id=crypto.randomUUID(),now=new Date().toISOString(),photoKey=null,photoName=null,photoType=null;if(photo instanceof File&&photo.size>0){if(photo.size>MAX_PHOTO)return fail('사진은 8MB보다 작아야 해요.',413);if(!photo.type.startsWith('image/'))return fail('사진 파일만 올릴 수 있어요.');photoKey=projectId+'/'+id;photoName=photo.name.slice(0,200);photoType=photo.type;await env.BUCKET.put(photoKey,photo,{httpMetadata:{contentType:photoType},customMetadata:{originalName:photoName}})}var height=text(b.heightCm)===''?null:Number(b.heightCm),leaves=text(b.leafCount)===''?null:Number(b.leafCount);try{await env.DB.batch([env.DB.prepare('INSERT INTO observations (id,project_id,observed_at,weather,title,note,changes,height_cm,leaf_count,photo_key,photo_name,photo_type,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,projectId,observed,text(b.weather).slice(0,20),title,note,text(b.changes).slice(0,1000),Number.isFinite(height)?height:null,Number.isFinite(leaves)?Math.round(leaves):null,photoKey,photoName,photoType,now),env.DB.prepare('UPDATE projects SET updated_at=? WHERE id=?').bind(now,projectId)])}catch(e){if(photoKey)await env.BUCKET.delete(photoKey);throw e}var row=await env.DB.prepare('SELECT * FROM observations WHERE id=?').bind(id).first();return json({observation:row},201)}
async function observationForEdit(id,session,env){var obs=await env.DB.prepare('SELECT o.* FROM observations o JOIN projects p ON p.id=o.project_id WHERE o.id=? AND p.class_code=?').bind(id,session.class_code).first();if(!obs)return {error:fail('관찰 기록을 찾을 수 없어요.',404)};var project=await projectForClass(obs.project_id,session,env);if(!project)return {error:fail('식물 기록을 찾을 수 없어요.',404)};if(!canEdit(session,project))return {error:fail('다른 친구의 관찰일지는 수정할 수 없어요.',403)};return {observation:obs,project:project}}
async function updateObservation(request,session,env,id){var found=await observationForEdit(id,session,env);if(found.error)return found.error;var old=found.observation,type=request.headers.get('content-type')||'',b,photo;if(type.includes('multipart/form-data')){var form=await request.formData();b=Object.fromEntries(form.entries());photo=form.get('photo')}else b=await request.json();var observed=text(b.observedAt),title=text(b.title).slice(0,100),note=text(b.note).slice(0,1500);if(!observed||!title||!note)return fail('날짜, 제목, 관찰한 모습을 모두 입력해 주세요.');var photoKey=old.photo_key,photoName=old.photo_name,photoType=old.photo_type,newKey=null,removeOld=false;if(photo instanceof File&&photo.size>0){if(photo.size>MAX_PHOTO)return fail('사진은 8MB보다 작아야 해요.',413);if(!photo.type.startsWith('image/'))return fail('사진 파일만 올릴 수 있어요.');newKey=old.project_id+'/'+old.id+'-'+crypto.randomUUID().slice(0,8);photoName=photo.name.slice(0,200);photoType=photo.type;await env.BUCKET.put(newKey,photo,{httpMetadata:{contentType:photoType},customMetadata:{originalName:photoName}});removeOld=!!old.photo_key;photoKey=newKey}else if(text(b.removePhoto)==='1'&&old.photo_key){removeOld=true;photoKey=null;photoName=null;photoType=null}var height=text(b.heightCm)===''?null:Number(b.heightCm),leaves=text(b.leafCount)===''?null:Number(b.leafCount),now=new Date().toISOString();try{await env.DB.batch([env.DB.prepare('UPDATE observations SET observed_at=?,weather=?,title=?,note=?,changes=?,height_cm=?,leaf_count=?,photo_key=?,photo_name=?,photo_type=? WHERE id=?').bind(observed,text(b.weather).slice(0,20),title,note,text(b.changes).slice(0,1000),Number.isFinite(height)?height:null,Number.isFinite(leaves)?Math.round(leaves):null,photoKey,photoName,photoType,old.id),env.DB.prepare('UPDATE projects SET updated_at=? WHERE id=?').bind(now,old.project_id)])}catch(e){if(newKey)await env.BUCKET.delete(newKey);throw e}if(removeOld)await env.BUCKET.delete(old.photo_key);var row=await env.DB.prepare('SELECT * FROM observations WHERE id=?').bind(old.id).first();return json({observation:row})}
async function deleteObservation(session,env,id){var found=await observationForEdit(id,session,env);if(found.error)return found.error;var old=found.observation;await env.DB.batch([env.DB.prepare('DELETE FROM observations WHERE id=?').bind(old.id),env.DB.prepare('UPDATE projects SET updated_at=? WHERE id=?').bind(new Date().toISOString(),old.project_id)]);if(old.photo_key)await env.BUCKET.delete(old.photo_key);return json({ok:true})}
async function servePhoto(path,session,env){var key=decodeURIComponent(path.slice('/api/photos/'.length));if(!key||key.includes('..'))return fail('사진을 찾을 수 없어요.',404);var projectId=key.split('/')[0],project=await projectForClass(projectId,session,env);if(!project)return fail('사진을 찾을 수 없어요.',404);var object=await env.BUCKET.get(key);if(!object)return fail('사진을 찾을 수 없어요.',404);var headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('cache-control','private, max-age=3600');return new Response(object.body,{headers:headers})}

async function listStudents(session,env){if(session.role!=='teacher')return fail('교사만 사용할 수 있어요.',403);var r=await env.DB.prepare("SELECT id,name,must_change_pin,locked_until,created_at FROM accounts WHERE class_code=? AND role='student' ORDER BY name").bind(session.class_code).all();return json({students:r.results||[]})}
async function addStudent(request,session,env){if(session.role!=='teacher')return fail('교사만 사용할 수 있어요.',403);var b=await request.json(),name=cleanName(b.name);if(!name)return fail('학생 이름을 입력해 주세요.');var existing=await env.DB.prepare("SELECT id FROM accounts WHERE class_code=? AND name=? AND role='student'").bind(session.class_code,name).first();if(existing)return fail('이미 등록된 학생 이름이에요.',409);var ph=await newPinHash('0000'),now=new Date().toISOString(),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO accounts (id,class_code,name,role,pin_salt,pin_hash,must_change_pin,created_at,updated_at) VALUES (?,?,?,'student',?,?,1,?,?)").bind(id,session.class_code,name,ph.salt,ph.hash,now,now).run();return json({student:{id:id,name:name,must_change_pin:true}},201)}
function studentTemplate(session){if(session.role!=='teacher')return fail('교사만 사용할 수 있어요.',403);return new Response('\uFEFF이름\r\n김민지\r\n이준호\r\n',{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="student-list-template.csv"','cache-control':'no-store'}})}
async function importStudents(request,session,env){if(session.role!=='teacher')return fail('교사만 사용할 수 있어요.',403);var form=await request.formData(),file=form.get('file');if(!(file instanceof File)||!file.size)return fail('CSV 파일을 선택해 주세요.');if(file.size>1024*1024)return fail('CSV 파일은 1MB보다 작아야 해요.',413);var source=await csvText(file),rows=csvRows(source);if(rows.length&&/^sep\s*=/.test(normalizeHeader(rows[0][0])))rows.shift();if(!rows.length)return fail('CSV 파일에 학생 이름이 없어요.');var aliases=['이름','학생이름','성명','name','studentname'],headers=rows[0].map(normalizeHeader),nameIndex=headers.findIndex(function(x){return aliases.includes(x)});if(nameIndex<0)return fail('첫 번째 줄에서 이름 열을 찾지 못했어요. 이름, 학생 이름 또는 성명으로 적어 주세요.');var names=[],seen=new Set();rows.slice(1).forEach(function(row){var name=cleanName(row[nameIndex]);if(name&&!seen.has(name)){seen.add(name);names.push(name)}});if(!names.length)return fail('등록할 학생 이름을 입력해 주세요.');if(names.length>100)return fail('한 번에 최대 100명까지 등록할 수 있어요.');var existingResult=await env.DB.prepare("SELECT name FROM accounts WHERE class_code=? AND role='student'").bind(session.class_code).all(),existing=new Set((existingResult.results||[]).map(function(x){return x.name})),pending=names.filter(function(name){return !existing.has(name)});if(pending.length){var ph=await newPinHash('0000'),now=new Date().toISOString();await env.DB.batch(pending.map(function(name){return env.DB.prepare("INSERT INTO accounts (id,class_code,name,role,pin_salt,pin_hash,must_change_pin,created_at,updated_at) VALUES (?,?,?,'student',?,?,1,?,?)").bind(crypto.randomUUID(),session.class_code,name,ph.salt,ph.hash,now,now)}))}return json({added:pending.length,skipped:names.length-pending.length,total:names.length,names:pending})}
async function resetStudent(id,session,env){if(session.role!=='teacher')return fail('교사만 사용할 수 있어요.',403);var student=await env.DB.prepare("SELECT id FROM accounts WHERE id=? AND class_code=? AND role='student'").bind(id,session.class_code).first();if(!student)return fail('학생 계정을 찾을 수 없어요.',404);var ph=await newPinHash('0000');await env.DB.batch([env.DB.prepare('UPDATE accounts SET pin_salt=?,pin_hash=?,must_change_pin=1,failed_attempts=0,locked_until=NULL,updated_at=? WHERE id=?').bind(ph.salt,ph.hash,new Date().toISOString(),id),env.DB.prepare('DELETE FROM sessions WHERE account_id=?').bind(id)]);return json({ok:true})}

async function route(request,env){var url=new URL(request.url),p=url.pathname,m=request.method;if((p==='/'||p==='/index.html')&&m==='GET')return new Response(APP_HTML,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});if(p==='/assets/styles.css')return new Response(APP_CSS,{headers:{'content-type':'text/css; charset=utf-8','cache-control':'no-store'}});if(p==='/assets/app.js')return new Response(APP_JS,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});if(!env.DB||!env.BUCKET)return fail('저장 공간을 준비하는 중이에요. 잠시 후 다시 시도해 주세요.',503);if(p==='/api/auth/login'&&m==='POST')return login(request,env);if(p==='/api/auth/teacher-signup'&&m==='POST')return teacherSignup(request,env);if(p==='/api/auth/me'&&m==='GET')return me(request,env);if(p==='/api/auth/logout'&&m==='POST')return logout(request,env);var auth=await requireSession(request,env,p==='/api/auth/change-pin'||p==='/api/auth/logout');if(auth.error)return auth.error;var s=auth.session;if(p==='/api/auth/change-pin'&&m==='POST')return changePin(request,env,s);if(p==='/api/projects'&&m==='GET')return listProjects(s,env);if(p==='/api/projects'&&m==='POST')return createProject(request,s,env);if(p.startsWith('/api/projects/')&&m==='PATCH')return updateProject(request,s,env,decodeURIComponent(p.slice(14)));if(p==='/api/observations'&&m==='GET')return listObservations(url,s,env);if(p==='/api/observations'&&m==='POST')return createObservation(request,s,env);var obsMatch=p.match(/^\/api\/observations\/([^/]+)$/);if(obsMatch&&m==='PATCH')return updateObservation(request,s,env,decodeURIComponent(obsMatch[1]));if(obsMatch&&m==='DELETE')return deleteObservation(s,env,decodeURIComponent(obsMatch[1]));if(p.startsWith('/api/photos/')&&m==='GET')return servePhoto(p,s,env);if(p==='/api/admin/students'&&m==='GET')return listStudents(s,env);if(p==='/api/admin/students'&&m==='POST')return addStudent(request,s,env);if(p==='/api/admin/students/template.csv'&&m==='GET')return studentTemplate(s);if(p==='/api/admin/students/import'&&m==='POST')return importStudents(request,s,env);var match=p.match(/^\/api\/admin\/students\/([^/]+)\/reset$/);if(match&&m==='POST')return resetStudent(decodeURIComponent(match[1]),s,env);return fail('요청한 페이지를 찾을 수 없어요.',404)}
export default {async fetch(request,env){try{return await route(request,env)}catch(error){console.error(error);return fail('처리 중 문제가 생겼어요. 잠시 후 다시 시도해 주세요.',500)}}};
